FROM docker.io/golang:1.23-bookworm

RUN apt-get update && \
    apt-get install -y \
        sudo \
        protobuf-compiler \
        protoc-gen-go && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root
COPY bashrc.sh .bashrc
COPY bashrc.d .bashrc.d
