FROM docker.io/golang:1.23-bookworm

RUN apt-get update && \
    apt-get install -y \
        sudo \
        protobuf-compiler \
        protoc-gen-go && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd developer && \
    echo '%sudo ALL=(ALL:ALL) ALL' > /etc/sudoers.d/developer

USER developer
WORKDIR /home/developer

COPY ./bashrc.sh ./.bashrc
COPY ./ps1.sh ./.bashrc.d/